name: GitHub README Activity Section Updater
description: Updates your personal README with the recent GitHub activity of a user. Fork of https://github.com/jamesgeorge007/github-activity-readme.
author: MadeByThePinsHub

inputs:
  USERNAME:
    description: 'Your GitHub username'
    default: ${{ github.repository_owner }}

branding:
  color: yellow
  icon: activity

runs:
  using: node12
  main: dist/index.js
